### ISSUE TITLE
ctest still saying it is not patched

### ISSUE THREAD

**Issue by JaySea77** [ITotalJustice/sys-patch#2]
I have installed version 1.4.2 and in the log it stay says patched in green for ctest. Wasn't this what was fixed in 1.4.1?
I have used the sigpatch updater to update my patches and these include the ctest patches right?

Edit:
After turning sys-patch on in sysmodules overlay, it goes to off after a few seconds. After going back to the sys-patch logging it now says ctest is patched in yellow. If I reboot it is green again and becomes yellow after running sys-patch again in sysmodules.

**Comment by ITotalJustice** [comment]
Yeah the sigpatches don't do the same patches I do (I think) thats why it says sys-patch patched it, because sys-patch overwrites the ctest patch.

When you run the sysmodule twice, it will show yellow for everything because the sysmodules are already patched and sys-patch sees that and assumes it was already patched by sigpatches

**Comment by JaySea77** [comment]
Though using Sigpatch-updater, wouldn’t it take your sigpatches?Obvious that it would show all yellow if you run it twice, my bad.Op 11 jun. 2023 om 19:50 heeft ITotalJustice ***@***.***> het volgende geschreven:﻿
Yeah the sigpatches don't do the same patches I do (I think) thats why it says sys-patch patched it, because sys-patch overwrites the ctest patch.
When you run the sysmodule twice, it will show yellow for everything because the sysmodules are already patched and sys-patch sees that and assumes it was already patched by sigpatches

**Comment by ITotalJustice** [comment]
> Though using Sigpatch-updater, wouldn’t it take your sigpatches?Obvious that it would show all yellow if you run it twice, my bad.Op 11 jun. 2023 om 19:50 heeft ITotalJustice ***@***.***> het volgende geschreven:﻿ Yeah the sigpatches don't do the same patches I do (I think) thats why it says sys-patch patched it, because sys-patch overwrites the ctest patch. When you run the sysmodule twice, it will show yellow for everything because the sysmodules are already patched and sys-patch sees that and assumes it was already patched by sigpatches —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

No, sigpatch updater downloads patches not created or uploaded by me. The person that creates the patches is more on the ball than me so it's better to download his haha. Not that ours would differ aside from ctest.

Anyway hopefully that cleared everything up :)

**Comment by JaySea77** [comment]
Yes, thank you for the explanation.
