### ISSUE TITLE
Error on Make

### ISSUE THREAD

**Issue by apeoplerson** [ITotalJustice/sys-patch#3]
Hello. So everything went great and everything was created in the /out. I just want to make sure these errors are okay to get. See below.

Failed to get system_resource_size (field not present).
Failed to get version (field not present).
Failed to get process_category (field not present).
Failed to get optimize_memory_allocation (field not present).
Failed to get disable_device_address_space_merge (field not present).
Failed to get signature_key_generation (field not present).
Failed to get program_id_range_min (field not present).
Failed to get program_id_range_max (field not present).
Failed to get program_id (field not present).

Everything was created though in /out. Should I be concerned or is this okay?

**Comment by ITotalJustice** [comment]
hi there. these are just warnings that npdmtool output if not every field is filled out in the .json file. these fields are optional so its okay. these same warnings will be shows in you build any sysmodule btw 😄 

hopefully this answers everything!
