### ISSUE TITLE
why is sysmmc patching enabled by default?

### ISSUE THREAD

**Issue by M1cha** [ITotalJustice/sys-patch#4]
Why is sysmmc patching enabled by default? Doesn't this risk a ban? Is there a way to undo the patches?

**Comment by impeeza** [comment]
the patch happens on fly at startup, so if you start emuMMC emmuMMC will be patched, the same on SysMMC, for enable/disable patching you can:

- Disable the sysmodule via sysmodule manager overlay or removing the `atmosphere\contents\420000000000000B\flags\boot2.flag` file
- change the `config\sys-patch\config.ini` file and disable the type of patch you don't want to be applied.
you don't need to "reverse" the patching all patching is done on memory, no NAND file is changed.

**Comment by M1cha** [comment]
Patches being in ram is very reassuring, thanks 👍
